name: Node CI

on:
  push:
    branches:
      - 'gh-pages'

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 'v16'
    - name: Install
      run: |
        npm ci
    - name: Build
      run: |
        npm run build
      env:
        CI: true
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: |
          dist